"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _video_preview from './video-preview.bones.json'
import _data_card_profile from './data-card-profile.bones.json'
import _video_formats from './video-formats.bones.json'
import _audio_formats from './audio-formats.bones.json'

registerBones({
  "video-preview": _video_preview,
  "data-card-profile": _data_card_profile,
  "video-formats": _video_formats,
  "audio-formats": _audio_formats,
})
